language: "ko-KR" # 리뷰 언어를 한국어로 설정
early_access: false # 실험적 기능 사용 여부

reviews:
  profile: "chill" # assertiveness: chill(부드러움) vs assertive(단호함)
  request_changes_workflow: false # 리뷰 봇이 직접 PR에 'Request Changes'를 할지 여부
  high_level_summary: true # PR의 전체적인 요약 제공
  auto_review:
    enabled: true # PR 생성 시 자동 리뷰 시작
    ignore_title_keywords: # 리뷰를 건너뛸 PR 제목 키워드
      - "Draft"
  
  path_instructions:
    - path: "**/*"
      instructions: |
        당신은 시니어 Java 백엔드 개발자입니다. 다음 기준에 맞춰 리뷰해주세요:

        1. **Java Code Quality**:
           - Stream API의 오용이나 가독성을 해치는 람다식이 없는지 봐주세요.
           - Lombok(@Data, @Setter 등)의 남용으로 인한 Side Effect 가능성을 체크해주세요.

        2. **Security**:
           - SQL Injection이나 XSS 취약점이 없는지 확인하세요.

        3. **JPA & Database Performance**:
           - 연관 관계 매핑 시 `FetchType.EAGER`가 사용되지 않았는지 확인하세요. (항상 `LAZY` 권장)
           - 반복문 안에서 DB 쿼리가 발생하는 'N+1 문제'의 가능성이 있는지 체크해주세요.
           - `@Transactional` 어노테이션이 필요한 서비스 로직에 누락되지 않았는지 확인하세요.

chat:
  auto_reply: true # 코멘트에 대한 봇의 자동 응답
