language: "ko-KR" # λ¦¬λ·° μ–Έμ–΄λ¥Ό ν•κµ­μ–΄λ΅ μ„¤μ •
early_access: false # μ‹¤ν—μ  κΈ°λ¥ μ‚¬μ© μ—¬λ¶€

reviews:
  profile: "chill" # assertiveness: chill(λ¶€λ“λ¬μ›€) vs assertive(λ‹¨νΈν•¨)
  request_changes_workflow: false # λ¦¬λ·° λ΄‡μ΄ μ§μ ‘ PRμ— 'Request Changes'λ¥Ό ν• μ§€ μ—¬λ¶€
  high_level_summary: true # PRμ μ „μ²΄μ μΈ μ”μ•½ μ κ³µ
  auto_review:
    enabled: true # PR μƒμ„± μ‹ μλ™ λ¦¬λ·° μ‹μ‘
    ignore_title_keywords: # λ¦¬λ·°λ¥Ό κ±΄λ„λ›Έ PR μ λ© ν‚¤μ›λ“
      - "Draft"
  
  # π’΅ [μμ •λ¨] instructionsλ” reviews μ„Ήμ… λ‚΄λ¶€λ΅ λ“¤μ–΄μ™€μ•Ό ν•©λ‹λ‹¤.
  instructions: |
    λ‹Ήμ‹ μ€ μ‹λ‹μ–΄ Java λ°±μ—”λ“ κ°λ°μμ…λ‹λ‹¤. λ‹¤μ κΈ°μ¤€μ— λ§μ¶° λ¦¬λ·°ν•΄μ£Όμ„Έμ”:

    1. **Java Code Quality**:
       - Stream APIμ μ¤μ©μ΄λ‚ κ°€λ…μ„±μ„ ν•΄μΉλ” λλ‹¤μ‹μ΄ μ—†λ”μ§€ λ΄μ£Όμ„Έμ”.
       - Lombok(@Data, @Setter λ“±)μ λ‚¨μ©μΌλ΅ μΈν• Side Effect κ°€λ¥μ„±μ„ μ²΄ν¬ν•΄μ£Όμ„Έμ”.

    2. **Security**:
       - SQL Injectionμ΄λ‚ XSS μ·¨μ•½μ μ΄ μ—†λ”μ§€ ν™•μΈν•μ„Έμ”.

    3. **JPA & Database Performance**:
       - μ—°κ΄€ κ΄€κ³„ λ§¤ν•‘ μ‹ `FetchType.EAGER`κ°€ μ‚¬μ©λμ§€ μ•μ•λ”μ§€ ν™•μΈν•μ„Έμ”. (ν•­μƒ `LAZY` κ¶μ¥)
       - λ°λ³µλ¬Έ μ•μ—μ„ DB μΏΌλ¦¬κ°€ λ°μƒν•λ” 'N+1 λ¬Έμ 'μ κ°€λ¥μ„±μ΄ μλ”μ§€ μ²΄ν¬ν•΄μ£Όμ„Έμ”.
       - `@Transactional` μ–΄λ…Έν…μ΄μ…μ΄ ν•„μ”ν• μ„λΉ„μ¤ λ΅μ§μ— λ„λ½λμ§€ μ•μ•λ”μ§€ ν™•μΈν•μ„Έμ”.

chat:
  auto_reply: true # μ½”λ©νΈμ— λ€ν• λ΄‡μ μλ™ μ‘λ‹µ
